language: node_js

node_js:
  - 14

services:
  - docker

before_script:
  - make install

script:
  - make build

after_success:
  - echo "$QUAY_BOT_PASSWORD" | docker login --username "$QUAY_BOT_USERNAME" --password-stdin quay.io
  - make cbuild
  - make cpush
  - docker tag quay.io/konveyor/move2kube-ui:latest quay.io/konveyor/move2kube-ui:$TRAVIS_BRANCH
  - docker push quay.io/konveyor/move2kube-ui:$TRAVIS_BRANCH

notifications:
    email:
      recipients:
        - ashokponkumar@in.ibm.com
      on_success: never 
      on_failure: always
