version: "3"
services:
  move2kubeapi:
    image: quay.io/konveyor/move2kube-api:latest
    ports:
      - "8080:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./:/wksps"
  move2kubeui:
    image: quay.io/konveyor/move2kube-ui:latest
    environment:
      - MOVE2KUBEAPI=http://move2kubeapi:8080
    ports:
      - "8080:8080"