# permissions for end users to edit move2kubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: move2kube-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: move2kube-operator
    app.kubernetes.io/part-of: move2kube-operator
    app.kubernetes.io/managed-by: kustomize
  name: move2kube-editor-role
rules:
- apiGroups:
  - move2kube.konveyor.io
  resources:
  - move2kubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - move2kube.konveyor.io
  resources:
  - move2kubes/status
  verbs:
  - get
