apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for move2kube.konveyor.io/v1alpha1, Kind: Move2Kube
##
- apiGroups:
  - move2kube.konveyor.io
  resources:
  - move2kubes
  - move2kubes/status
  - move2kubes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "serviceaccounts"
  - "services"
  - "configmaps"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"
- verbs:
  - "*"
  apiGroups:
  - "security.openshift.io"
  resources:
  - "securitycontextconstraints"

#+kubebuilder:scaffold:rules
