apiVersion: move2kube.konveyor.io/v1alpha1
kind: Move2Kube
metadata:
  name: move2kube-sample
spec:
  # Default values copied from <project_dir>/helm-charts/move2kube/values.yaml
  deployment:
    api:
      cpu: 300m
      imageTag: ""
      initContainer: false
      memory: 1Gi
      privilegedPods: false
      replicas: 1
    authServer:
      cpu: 300m
      enable: false
      memory: 1Gi
      replicas: 1
    database:
      cpu: 300m
      enable: false
      memory: 1Gi
      replicas: 1
      startEmpty: true
  ingress:
    enable: true
    host: mydomain.com
    preferRoute: false
    tlsSecretName: ""
  persistentVolumeClaim:
    createNew: true
    enable: false
    name: ""
    readWriteMany: true
    storageClassName: ""
    storageSize: 1Gi
  secret:
    api:
      configYAML: ""
      createNew: true
      enable: false
      name: ""
    authServer:
      adminPassword: password
      adminUsername: admin
      createNew: true
      databasePassword: password
      databaseUsername: auth-server
      name: ""
      realmJSON: ""
      standaloneHAXML: ""
  securityContextContraints:
    enable: false
  serviceAccount:
    createNew: true
    enable: false
    name: ""
  
  
