{{- if and (.Values.deployment.authServer.enable) (.Values.secret.authServer.createNew) }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.secret.authServer.name | default (print .Release.Name "-auth-server") }}'
data:
  realm.json: "{{ .Values.secret.authServer.realmJSON | toString | b64enc }}"
  standalone-ha.xml: "{{ .Values.secret.authServer.standaloneHAXML | toString | b64enc }}"
{{- end }}
