apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-auth-server"
  labels:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-auth-server"
spec:
  type: ClusterIP
  ports:
    - name: "port-8081"
      port: 8081
      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-auth-server"
