apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-database"
spec:
  type: ClusterIP
  ports:
    - name: "port-5432"
      port: 5432
      targetPort: 5432
  selector:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-database"
