{{- if and (.Values.secret.api.enable) (.Values.secret.api.createNew) }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.secret.api.name | default (print .Release.Name "-move2kubeapi") }}'
data:
  config.yaml: "{{ .Values.secret.api.configYAML | toString | b64enc }}"
{{- end }}
