{{- if and (.Values.securityContextContraints.enable) (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "{{ .Release.Name }}-move2kube"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
users:
  - "system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.serviceAccount.name | default (print .Release.Name "-move2kube") }}"
fsGroup:
  type: RunAsAny
priority: 100
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: {{ .Values.deployment.api.privilegedPods }}
allowPrivilegedContainer: {{ .Values.deployment.api.privilegedPods }}
runAsUser:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowedCapabilities: []
defaultAddCapabilities: []
{{- end }}
