{{- if and (.Values.serviceAccount.enable) (.Values.serviceAccount.createNew) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.serviceAccount.name | default (print .Release.Name "-move2kube") }}'
{{- end }}
