name: PR Build

on:
  pull_request:
    branches:
      - "main"
      - "release-*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: make install
      - run: make build
