name: PR Build

on:
  pull_request:
    branches:
      - "main"
      - "release-*"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.16.0"
      - run: corepack enable
      - run: make install
      - run: make build
