name: Tag

on:
  repository_dispatch:
    types: [cli_tagged]

jobs:

  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ github.event.client_payload.message.tag }}
